import GetItemDto from './get-item.dto';

export const emptyGetItemDto: GetItemDto = {
  dp_id: '',
  dp_1cCode: '',
  dp_1cDescription: '',
  dp_1cIsFolder: false,
  dp_1cParentId: '',
  dp_seoTitle: '',
  dp_seoDescription: '',
  dp_seoKeywords: '',
  dp_seoUrlSegment: '',
  dp_textCharacteristics: '',
  dp_photos: '',
  dp_photos360: '',
  dp_photoUrl: '',
  dp_wholesaleQuantity: 0,
  dp_brand: '',
  dp_combinedName: '',
  dp_vendorIds: '',
  dp_ozonIds: '',
  dp_barcodes: '',
  dp_length: 0,
  dp_width: 0,
  dp_height: 0,
  dp_weight: 0,
  dp_cost: 0,
  dp_sortingIndex: 0,
  dp_youtubeIds: '',
  dp_currancy: '',
  dp_isHidden: false,
  dp_itemCategoryId: 0,
  dp_itemCharacteristics: [],
  dp_itemGalery: [],
};
